import type { StudioState } from "./types";

export const STORAGE_KEY = "relay-desk-v1";

export const seedState = (): StudioState => ({
  studioName: "Akaai Spaces",
  currentUserId: "tm-akshay",
  updatedAt: 1,
  team: [
    {
      id: "tm-akshay",
      name: "Akshay Suresh",
      role: "Principal",
      email: "akshay@akaaispaces.com",
      initials: "AS",
      color: "#7C4A2A",
    },
    {
      id: "tm-maya",
      name: "Maya Chen",
      role: "Account director",
      email: "maya@akaaispaces.com",
      initials: "MC",
      color: "#2F4F4A",
    },
    {
      id: "tm-jordan",
      name: "Jordan Ellis",
      role: "Creative director",
      email: "jordan@akaaispaces.com",
      initials: "JE",
      color: "#3F3A6B",
    },
    {
      id: "tm-aisha",
      name: "Aisha Rahman",
      role: "Video editor",
      email: "aisha@akaaispaces.com",
      initials: "AR",
      color: "#5A3A5A",
    },
    {
      id: "tm-priya",
      name: "Priya Shah",
      role: "Paid media",
      email: "priya@akaaispaces.com",
      initials: "PS",
      color: "#6B3A3A",
    },
    {
      id: "tm-sam",
      name: "Sam Okonkwo",
      role: "Posting & scheduling",
      email: "sam@akaaispaces.com",
      initials: "SO",
      color: "#3A5A6B",
    },
    {
      id: "tm-riley",
      name: "Riley Park",
      role: "Designer",
      email: "riley@akaaispaces.com",
      initials: "RP",
      color: "#5A4A2A",
    },
    {
      id: "tm-noah",
      name: "Noah Adler",
      role: "Copywriter",
      email: "noah@akaaispaces.com",
      initials: "NA",
      color: "#2A4A5A",
    },
  ],
  clients: [
    {
      id: "cl-harbor",
      name: "Harbor & Pine",
      industry: "Home & furniture",
      status: "active",
      contactName: "Elena Voss",
      contactEmail: "elena@harborandpine.com",
      website: "harborandpine.com",
      retainer: "$18k / month",
      notes:
        "Brand voice is quiet, material, unhurried. No discount language. Elena reviews hero assets personally; social can go through Maya.",
    },
    {
      id: "cl-solstice",
      name: "Solstice Athletics",
      industry: "Running apparel",
      status: "active",
      contactName: "Marcus Hale",
      contactEmail: "marcus@solstice.run",
      website: "solstice.run",
      retainer: "$24k / month + media",
      notes:
        "Performance first. UTM discipline is non-negotiable. Creative must feel like race-week energy, not gym bro.",
    },
    {
      id: "cl-brightwell",
      name: "Brightwell Dental",
      industry: "Local healthcare",
      status: "onboarding",
      contactName: "Dr. Amina Brightwell",
      contactEmail: "amina@brightwell.dental",
      website: "brightwell.dental",
      retainer: "$8k / month",
      notes:
        "New logo lockup arriving Sep 22. Do not publish paid until brand kit is in. HIPAA: no patient photos without release.",
    },
  ],
  campaigns: [
    {
      id: "camp-hp-fall",
      clientId: "cl-harbor",
      name: "Fall Home 2026",
      objective:
        "Launch the walnut + linen collection. Drive 30% of Q4 site revenue from the lookbook and 4 flagship SKUs.",
      status: "in-market",
      startDate: "2026-09-08",
      endDate: "2026-10-20",
      channels: ["Instagram", "Email", "Paid social", "Landing page", "PR"],
      budget: "$42,000",
      kpis: "Lookbook CVR 3.2% · email revenue $28k · 1.2M paid impressions",
      ownerId: "tm-maya",
    },
    {
      id: "camp-hp-social",
      clientId: "cl-harbor",
      name: "Harbor always-on social",
      objective: "Three brand posts a week. Craft, process, rooms — never product dumps.",
      status: "always-on",
      startDate: "2026-01-06",
      endDate: "2026-12-18",
      channels: ["Instagram", "Pinterest", "Email"],
      budget: "Inside retainer",
      kpis: "Save rate 4% · site sessions from IG +18% YoY",
      ownerId: "tm-sam",
    },
    {
      id: "camp-sol-marathon",
      clientId: "cl-solstice",
      name: "NYC Marathon drop",
      objective:
        "Co-branded racing kit drop the week of the marathon. Sell through limited SKUs and capture email for spring.",
      status: "in-market",
      startDate: "2026-09-15",
      endDate: "2026-11-08",
      channels: ["TikTok", "Instagram", "Email", "Paid social", "Influencer", "Events"],
      budget: "$85,000",
      kpis: "Sell-through 90% · 8k new emails · 40 UGC pieces",
      ownerId: "tm-jordan",
    },
    {
      id: "camp-sol-perf",
      clientId: "cl-solstice",
      name: "Q4 performance always-on",
      objective: "Prospecting + retargeting on Meta and Google. Protect MER while we scale the drop.",
      status: "always-on",
      startDate: "2026-09-01",
      endDate: "2026-12-31",
      channels: ["Paid social", "Paid search"],
      budget: "$120,000 media",
      kpis: "MER 3.4 · CAC under $38 · branded search +12%",
      ownerId: "tm-priya",
    },
    {
      id: "camp-bw-new",
      clientId: "cl-brightwell",
      name: "New patient launch",
      objective: "Local awareness + new-patient bookings once the brand kit lands.",
      status: "planning",
      startDate: "2026-09-29",
      endDate: "2026-11-30",
      channels: ["Paid search", "Instagram", "Landing page"],
      budget: "$12,000",
      kpis: "40 new-patient forms / month · $90 CPL",
      ownerId: "tm-maya",
    },
  ],
  milestones: [
    { id: "ms-1", campaignId: "camp-hp-fall", title: "Lookbook live", date: "2026-09-08", done: true },
    { id: "ms-2", campaignId: "camp-hp-fall", title: "Press kit to editors", date: "2026-09-16", done: false },
    { id: "ms-3", campaignId: "camp-hp-fall", title: "Hero film live", date: "2026-09-22", done: false },
    { id: "ms-4", campaignId: "camp-hp-fall", title: "Mid-campaign report", date: "2026-09-29", done: false },
    { id: "ms-5", campaignId: "camp-hp-fall", title: "Wrap & learnings", date: "2026-10-21", done: false },
    { id: "ms-6", campaignId: "camp-sol-marathon", title: "Influencer kits ship", date: "2026-09-18", done: false },
    { id: "ms-7", campaignId: "camp-sol-marathon", title: "Drop day", date: "2026-10-27", done: false },
    { id: "ms-8", campaignId: "camp-sol-marathon", title: "Race-week content blitz", date: "2026-11-01", done: false },
    { id: "ms-9", campaignId: "camp-bw-new", title: "Brand kit lock", date: "2026-09-22", done: false },
    { id: "ms-10", campaignId: "camp-bw-new", title: "Landing page QA", date: "2026-09-26", done: false },
    { id: "ms-11", campaignId: "camp-bw-new", title: "Paid go-live", date: "2026-09-29", done: false },
    { id: "ms-12", campaignId: "camp-sol-perf", title: "Creative refresh #2", date: "2026-09-16", done: false },
  ],
  deliverables: [
    {
      id: "dv-1",
      campaignId: "camp-hp-fall",
      clientId: "cl-harbor",
      title: "Fall lookbook email — walnut collection",
      type: "email",
      channel: "Email",
      status: "live",
      assigneeId: "tm-noah",
      date: "2026-09-08",
      time: "09:00",
      notes: "Segment: past purchasers + lookbook waitlist.",
    },
    {
      id: "dv-2",
      campaignId: "camp-hp-social",
      clientId: "cl-harbor",
      title: "Workshop stills — drawer joinery",
      type: "social post",
      channel: "Instagram",
      status: "live",
      assigneeId: "tm-sam",
      date: "2026-09-15",
      time: "11:00",
      notes: "",
    },
    {
      id: "dv-3",
      campaignId: "camp-hp-fall",
      clientId: "cl-harbor",
      title: "Carousel: 4 rooms, one palette",
      type: "carousel",
      channel: "Instagram",
      status: "scheduled",
      assigneeId: "tm-sam",
      date: "2026-09-16",
      time: "10:30",
      notes: "Caption locked. Cover is slide 2.",
    },
    {
      id: "dv-4",
      campaignId: "camp-hp-fall",
      clientId: "cl-harbor",
      title: "Press kit PDF + 12 stills",
      type: "press",
      channel: "PR",
      status: "client-review",
      assigneeId: "tm-maya",
      date: "2026-09-16",
      time: "14:00",
      notes: "Elena reviewing quotes. Do not send to editors until she signs off.",
    },
    {
      id: "dv-5",
      campaignId: "camp-sol-perf",
      clientId: "cl-solstice",
      title: "Meta prospecting — 6 new 1:1 cuts",
      type: "ad creative",
      channel: "Paid social",
      status: "scheduled",
      assigneeId: "tm-priya",
      date: "2026-09-16",
      time: "13:00",
      notes: "Kill last week's UGC set after 4pm.",
    },
    {
      id: "dv-6",
      campaignId: "camp-sol-marathon",
      clientId: "cl-solstice",
      title: "Teaser reel — kit in the rain",
      type: "reel / short",
      channel: "TikTok",
      status: "internal-review",
      assigneeId: "tm-jordan",
      date: "2026-09-16",
      time: "16:30",
      notes: "Need sound bed licensed. Jordan reviewing cut 3.",
    },
    {
      id: "dv-7",
      campaignId: "camp-sol-marathon",
      clientId: "cl-solstice",
      title: "Waitlist email: 6 weeks out",
      type: "email",
      channel: "Email",
      status: "draft",
      assigneeId: "tm-noah",
      date: "2026-09-17",
      time: "08:30",
      notes: "",
    },
    {
      id: "dv-8",
      campaignId: "camp-hp-social",
      clientId: "cl-harbor",
      title: "Stories: linen drape process",
      type: "social post",
      channel: "Instagram",
      status: "draft",
      assigneeId: "tm-riley",
      date: "2026-09-17",
      time: "12:00",
      notes: "",
    },
    {
      id: "dv-9",
      campaignId: "camp-sol-marathon",
      clientId: "cl-solstice",
      title: "Influencer unboxing brief (8 creators)",
      type: "brief",
      channel: "Influencer",
      status: "approved",
      assigneeId: "tm-maya",
      date: "2026-09-18",
      time: "10:00",
      notes: "Kits leave warehouse Thursday.",
    },
    {
      id: "dv-10",
      campaignId: "camp-hp-fall",
      clientId: "cl-harbor",
      title: "Hero film — 30s cutdown",
      type: "video",
      channel: "YouTube",
      status: "draft",
      assigneeId: "tm-jordan",
      date: "2026-09-22",
      time: "09:00",
      notes: "Color grade due Friday.",
    },
    {
      id: "dv-11",
      campaignId: "camp-bw-new",
      clientId: "cl-brightwell",
      title: "New-patient landing page copy",
      type: "landing page",
      channel: "Landing page",
      status: "briefing",
      assigneeId: "tm-noah",
      date: "2026-09-19",
      time: "11:00",
      notes: "Waiting on brand kit. Outline only.",
    },
    {
      id: "dv-12",
      campaignId: "camp-sol-perf",
      clientId: "cl-solstice",
      title: "Google RSA refresh — racing kit",
      type: "ad creative",
      channel: "Paid search",
      status: "live",
      assigneeId: "tm-priya",
      date: "2026-09-15",
      time: "09:00",
      notes: "",
    },
    {
      id: "dv-13",
      campaignId: "camp-hp-fall",
      clientId: "cl-harbor",
      title: "Friday house list: styling tips",
      type: "email",
      channel: "Email",
      status: "draft",
      assigneeId: "tm-noah",
      date: "2026-09-19",
      time: "09:00",
      notes: "",
    },
    {
      id: "dv-14",
      campaignId: "camp-sol-marathon",
      clientId: "cl-solstice",
      title: "Creator TikTok stitch pack",
      type: "reel / short",
      channel: "TikTok",
      status: "briefing",
      assigneeId: "tm-sam",
      date: "2026-09-20",
      time: "15:00",
      notes: "",
    },
  ],
  tasks: [
    {
      id: "tk-1",
      title: "Send Fall Home press kit after Elena signs off",
      details: "To Architectural Digest, Sight Unseen, Domino, Cereal. BCC Elena.",
      status: "blocked",
      priority: "urgent",
      dueDate: "2026-09-16",
      assigneeId: "tm-maya",
      clientId: "cl-harbor",
      campaignId: "camp-hp-fall",
    },
    {
      id: "tk-2",
      title: "Swap Meta prospecting creatives at 1pm",
      details: "Pause fatigued UGC. Launch 6 new 1:1s. Check frequency cap.",
      status: "doing",
      priority: "high",
      dueDate: "2026-09-16",
      assigneeId: "tm-priya",
      clientId: "cl-solstice",
      campaignId: "camp-sol-perf",
    },
    {
      id: "tk-3",
      title: "Internal review: rain teaser reel",
      details: "Cut 3. Confirm licensed audio. Jordan + Sam.",
      status: "doing",
      priority: "high",
      dueDate: "2026-09-16",
      assigneeId: "tm-jordan",
      clientId: "cl-solstice",
      campaignId: "camp-sol-marathon",
    },
    {
      id: "tk-4",
      title: "Publish Harbor carousel at 10:30",
      details: "Already scheduled in Meta. Confirm it went live and reply to first comments.",
      status: "todo",
      priority: "medium",
      dueDate: "2026-09-16",
      assigneeId: "tm-sam",
      clientId: "cl-harbor",
      campaignId: "camp-hp-fall",
    },
    {
      id: "tk-5",
      title: "Color grade hero film",
      details: "Match lookbook stills. Delivery Friday for Elena.",
      status: "todo",
      priority: "high",
      dueDate: "2026-09-18",
      assigneeId: "tm-jordan",
      clientId: "cl-harbor",
      campaignId: "camp-hp-fall",
    },
    {
      id: "tk-6",
      title: "Warehouse: pack 8 influencer kits",
      details: "Sizes per sheet in Drive. Include handwritten note.",
      status: "todo",
      priority: "high",
      dueDate: "2026-09-17",
      assigneeId: "tm-maya",
      clientId: "cl-solstice",
      campaignId: "camp-sol-marathon",
    },
    {
      id: "tk-7",
      title: "Draft Brightwell brand voice one-pager",
      details: "Calm, clinical, human. No scare copy. Share with Amina Friday.",
      status: "todo",
      priority: "medium",
      dueDate: "2026-09-19",
      assigneeId: "tm-noah",
      clientId: "cl-brightwell",
      campaignId: "camp-bw-new",
    },
    {
      id: "tk-8",
      title: "Weekly numbers for Solstice stand-up",
      details: "MER, CAC, creative fatigue, waitlist adds.",
      status: "todo",
      priority: "medium",
      dueDate: "2026-09-16",
      assigneeId: "tm-priya",
      clientId: "cl-solstice",
      campaignId: "camp-sol-perf",
    },
    {
      id: "tk-9",
      title: "Rewrite waitlist email subject lines (5)",
      details: "Marcus wants less hype, more race.",
      status: "todo",
      priority: "medium",
      dueDate: "2026-09-17",
      assigneeId: "tm-noah",
      clientId: "cl-solstice",
      campaignId: "camp-sol-marathon",
    },
    {
      id: "tk-10",
      title: "Book photographer for Brightwell clinic",
      details: "After brand kit. Empty chairs, light, no patients.",
      status: "todo",
      priority: "low",
      dueDate: "2026-09-23",
      assigneeId: "tm-riley",
      clientId: "cl-brightwell",
      campaignId: "camp-bw-new",
    },
    {
      id: "tk-11",
      title: "QA lookbook PDP modules on mobile",
      details: "Reported spacing bug on iPhone SE.",
      status: "done",
      priority: "high",
      dueDate: "2026-09-12",
      assigneeId: "tm-riley",
      clientId: "cl-harbor",
      campaignId: "camp-hp-fall",
    },
    {
      id: "tk-12",
      title: "Principal review: marathon drop timeline",
      details: "Akshay with Maya and Jordan. 20 minutes.",
      status: "todo",
      priority: "high",
      dueDate: "2026-09-16",
      assigneeId: "tm-akshay",
      clientId: "cl-solstice",
      campaignId: "camp-sol-marathon",
    },
  ],
  recaps: [
    {
      id: "rc-1",
      title: "Week of Sep 8 — studio close",
      type: "weekly",
      date: "2026-09-12",
      authorId: "tm-maya",
      shipped:
        "Harbor lookbook and launch email went live Monday. Solstice RSA refresh live. Always-on Harbor joinery post published.",
      next: "Press kit, Meta creative swap, marathon teaser cut, Brightwell voice one-pager.",
      blockers: "Elena still on press quotes. Brightwell brand kit delayed to Sep 22.",
      notes: "Team energy is good. Protect Jordan’s grade time this week — too many reviews stacked.",
    },
    {
      id: "rc-2",
      title: "Harbor Fall Home kickoff notes",
      type: "client-meeting",
      date: "2026-09-04",
      authorId: "tm-maya",
      clientId: "cl-harbor",
      campaignId: "camp-hp-fall",
      shipped: "",
      next: "Lookbook live Sep 8. Film Sep 22. Mid-campaign report Sep 29.",
      blockers: "Need final walnut stain name from product.",
      notes:
        "Elena: no lifestyle models in ads. Rooms only. She will personally approve film and press. Social can move without her if it matches the lookbook.",
    },
    {
      id: "rc-3",
      title: "Monday close — Sep 15",
      type: "daily-close",
      date: "2026-09-15",
      authorId: "tm-akshay",
      shipped: "Harbor workshop stills. Solstice Google RSA. Influencer brief approved.",
      next: "Tomorrow is a heavy publish day: carousel, press (if signed), Meta swap, teaser review.",
      blockers: "Press still with Elena.",
      notes: "Remind Priya to post the MER snapshot in Slack before stand-up.",
    },
    {
      id: "rc-4",
      title: "Solstice marathon — creative lock",
      type: "campaign",
      date: "2026-09-11",
      authorId: "tm-jordan",
      clientId: "cl-solstice",
      campaignId: "camp-sol-marathon",
      shipped: "Kit photography selected. Colorway named Night Harbor.",
      next: "Rain teaser, waitlist email, creator kits Thursday.",
      blockers: "Audio license for teaser.",
      notes: "Marcus liked the quieter end-card. Keep the logo small.",
    },
  ],
  videoJobs: [
    {
      id: "vid-rain",
      title: "Solstice rain teaser — 15s + 30s",
      brief:
        "Cut 3 of the rain teaser. 9:16 for TikTok/Reels, 1:1 for feed. End card small. Licensed audio only. Aisha: download the raw clips, edit, upload the finals. Sam: once finals are in, download and schedule.",
      clientId: "cl-solstice",
      campaignId: "camp-sol-marathon",
      status: "with-editor",
      dueDate: "2026-09-16",
      platforms: ["TikTok", "Instagram", "YouTube"],
      editorId: "tm-aisha",
      posterId: "tm-sam",
      sourceFiles: [],
      finalFiles: [],
    },
    {
      id: "vid-hero",
      title: "Harbor Fall Home hero film",
      brief:
        "30s lookbook film + 6s bumper. Rooms only, no models. Color grade to match walnut stills. Elena reviews before posting.",
      clientId: "cl-harbor",
      campaignId: "camp-hp-fall",
      status: "need-files",
      dueDate: "2026-09-22",
      platforms: ["Instagram", "YouTube", "Paid social"],
      editorId: "tm-aisha",
      posterId: "tm-sam",
      sourceFiles: [],
      finalFiles: [],
    },
    {
      id: "vid-joinery",
      title: "Harbor joinery process reel",
      brief:
        "Always-on craft reel. Quiet, no VO. Captions burned in. Sam posts Thursday.",
      clientId: "cl-harbor",
      campaignId: "camp-hp-social",
      status: "ready-to-post",
      dueDate: "2026-09-18",
      platforms: ["Instagram"],
      editorId: "tm-aisha",
      posterId: "tm-sam",
      sourceFiles: [],
      finalFiles: [],
    },
  ],
});
